### ISSUE TITLE
Create Example of Backstage API

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/backstage#102]
URL: https://backstage.ortelius.io/api-docs?filters%5Bkind%5D=api&filters%5Buser%5D=all

Backstage has the API functionality but we haven't used it yet. This issue is to explore it more and see how it looks. 

Lets use one of the Platform apps we use. For example look for the ArgoCD api in the repo, maybe there is a swagger file you use, im not sure how backstage wants it. 

you can use any app that is the easiest to test it.

**Comment by itisaby** [comment]
Ok I am looking into it

**Comment by itisaby** [comment]
I have found a very good example that is implemented in backstage, u can check it [here](https://github.com/backstage/backstage/blob/master/plugins/api-docs/README.md). Also, the definitions for the swagger ui are also given [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/apis/petstore-api.yaml). With the help of these we can make create an example. I am looking into the ARGO CD one, I am trying it out by myself. I will let you know.
